services:
    forumhulp.cron.prune_logs:
        class: forumhulp\prunelogs\cron\task\core\prunelogs
        arguments:
            - '@config'
            - '@user'
            - '@dbal.conn'
            - '@log'
        calls:
            - [set_name, [forumhulp.cron.prune_logs]]
        tags:
            - { name: cron.task }
    forumhulp.prunelogs.listener:
        class: forumhulp\prunelogs\event\listener
        arguments:
            - '@controller.helper'
        tags:
            - { name: event.listener }