services:
    cron.task.core.prune_logs:
        class: forumhulp\prune_logs\cron\task\core\prune_logs
        arguments:
            - @config
            - @dbal.conn
            - @log
        calls:
            - [set_name, [cron.task.core.prune_logs]]
        tags:
            - { name: cron.task }
    forumhulp.prune_logs.listener:
        class: forumhulp\prune_logs\event\listener
        arguments:
            - @controller.helper
        tags:
            - { name: event.listener }